package dao;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import lombok.*;
import org.joda.time.LocalDateTime;

import java.time.LocalDate;
import java.util.Date;

@Getter
@Setter
@ToString
@AllArgsConstructor
@NoArgsConstructor

@DynamoDBTable(tableName = "LibraryTable")
public class Book {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBRangeKey(attributeName = "type")
    private String itemType = "book";
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "titleIndex")
    @DynamoDBAttribute(attributeName = "title")
    private String title;
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "categoryIndex")
    @DynamoDBAttribute(attributeName = "category")
    private String category;
    @DynamoDBAttribute(attributeName = "status")
    private String status;
    @DynamoDBAttribute(attributeName = "rentedBy")
    private String rentedBy;
    @DynamoDBAttribute(attributeName = "bookedBy")
    private String bookedBy;
    @DynamoDBAttribute(attributeName = "rentDate")
    private String rentDate;
    @DynamoDBAttribute(attributeName = "bookingEndDate")
    private String bookingEndDate;
    @DynamoDBAttribute(attributeName = "rentPeriod")
    private int rentPeriod;
    @DynamoDBAttribute(attributeName = "removalDate")
    private String removalDate;
}
