package dao;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import lombok.*;

import java.time.ZoneId;
import java.time.ZonedDateTime;

@Getter
@Setter
@ToString
@AllArgsConstructor
@NoArgsConstructor

@DynamoDBTable(tableName = "LibraryTable")
public class History {
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBRangeKey(attributeName = "type")
    private String itemType = "history";
    @DynamoDBAttribute(attributeName = "title")
    private String title;
    @DynamoDBAttribute(attributeName = "category")
    private String category;
    @DynamoDBAttribute(attributeName = "status")
    private String status;
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "rentedByIndex")
    @DynamoDBAttribute(attributeName = "rentedBy")
    private String rentedBy;
    @DynamoDBAttribute(attributeName = "bookedBy")
    private String bookedBy;
    @DynamoDBAttribute(attributeName = "rentDate")
    private String rentDate;
    @DynamoDBAttribute(attributeName = "returnDate")
    private String returnDate;
    @DynamoDBAttribute(attributeName = "rentPeriod")
    private int rentPeriod;
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "bookIdIndex")
    @DynamoDBAttribute(attributeName = "bookId")
    private String bookId;


    public History(Book book){
        title = book.getTitle();
        category = book.getCategory();
        status = book.getStatus();
        rentedBy = book.getRentedBy();
        bookedBy = book.getBookedBy();
        rentDate = book.getRentDate();
        returnDate = ZonedDateTime.now(ZoneId.of("Europe/Warsaw")).toLocalDate().toString();
        rentPeriod = book.getRentPeriod();
        bookId = book.getId();

    }
}
