package dao;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import lombok.*;

@Getter
@Setter
@ToString
@AllArgsConstructor
@NoArgsConstructor

@DynamoDBTable(tableName = "LibraryTable")
public class Person {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "typeIndex")
    @DynamoDBRangeKey(attributeName = "type")
    private String itemType = "person";
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "nameIndex")
    @DynamoDBAttribute(attributeName = "name")
    private String name;
    @DynamoDBAttribute(attributeName = "secondName")
    private String secondName;
    @DynamoDBAttribute(attributeName = "lastName")
    private String lastName;
    @DynamoDBAttribute(attributeName = "email")
    private String email;
    @DynamoDBAttribute(attributeName = "status")
    private String status;


}
